### ISSUE TITLE
panic: ./route53-kubernetes flag redefined: log_dir

### ISSUE THREAD

**Issue by alexdej** [wearemolecule/route53-kubernetes#20] opened 2016-09-23 15:02 UTC
Caveat: I'm new to golang so entirely possible I've making a noob mistake here but two hours into a small patch and I still can't seem to be able to get a working binary for this project. Any help/guidance would be appreciated!

Build steps (ubuntu 14.04):
1. `glide install`
2. `make build`

Runtime error:

```
./route53-kubernetes flag redefined: log_dir
panic: ./route53-kubernetes flag redefined: log_dir

goroutine 1 [running]:
panic(0x141dd00, 0xc82000b750)
    /usr/lib/go/src/runtime/panic.go:464 +0x3e6
flag.(*FlagSet).Var(0xc8200160c0, 0x7f3538da56a0, 0xc82000b700, 0x19d0000, 0x7, 0x1b76fc0, 0x2f)
    /usr/lib/go/src/flag/flag.go:776 +0x454
flag.(*FlagSet).StringVar(0xc8200160c0, 0xc82000b700, 0x19d0000, 0x7, 0x0, 0x0, 0x1b76fc0, 0x2f)
    /usr/lib/go/src/flag/flag.go:679 +0xc7
flag.(*FlagSet).String(0xc8200160c0, 0x19d0000, 0x7, 0x0, 0x0, 0x1b76fc0, 0x2f, 0xc82000b6f0)
    /usr/lib/go/src/flag/flag.go:692 +0x83
flag.String(0x19d0000, 0x7, 0x0, 0x0, 0x1b76fc0, 0x2f, 0x7f3538da5918)
    /usr/lib/go/src/flag/flag.go:699 +0x5f
route53-kubernetes/vendor/k8s.io/kubernetes/vendor/github.com/golang/glog.init()
    /home/ubuntu/go/src/route53-kubernetes/vendor/k8s.io/kubernetes/vendor/github.com/golang/glog/glog_file.go:41 +0x13e
route53-kubernetes/vendor/k8s.io/kubernetes/pkg/labels.init()
    /home/ubuntu/go/src/route53-kubernetes/vendor/k8s.io/kubernetes/pkg/labels/selector.go:808 +0x5b
route53-kubernetes/vendor/k8s.io/kubernetes/pkg/api/unversioned.init()
    /home/ubuntu/go/src/route53-kubernetes/vendor/k8s.io/kubernetes/pkg/api/unversioned/well_known_labels.go:30 +0x6f
route53-kubernetes/vendor/k8s.io/kubernetes/pkg/api.init()
    /home/ubuntu/go/src/route53-kubernetes/vendor/k8s.io/kubernetes/pkg/api/types.go:2884 +0x64
main.init()
    /home/ubuntu/go/src/route53-kubernetes/service_listener.go:252 +0x80
```

Seems like a conflict with vendored deps, so I tried the following:
1. `glide install -v`
2. `make build`

This time I get a build error:

```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o route53-kubernetes .
# route53-kubernetes/vendor/golang.org/x/oauth2/google
vendor/golang.org/x/oauth2/google/default.go:92: undefined: metadata.OnGCE
vendor/golang.org/x/oauth2/google/google.go:117: undefined: metadata.OnGCE
vendor/golang.org/x/oauth2/google/google.go:124: undefined: metadata.Get
make: *** [build] Error 2
```

Any ideas? (Working on a fix that would use the service account credential and eliminate the need to mount a volume/etc)

**Comment by iterion** [comment] 2016-09-23 15:12
Weird, I just wiped away my vendor folder and tried your steps and couldn't reproduce. What glide version are you using? I think you can just use `glide -v`.

**Comment by alexdej** [comment] 2016-09-23 15:14
I have glide version v0.12.2

FWIW this seems to resolve the issue?
1. `glide install`
2. `find . -name glog`
3. `rm -rf ./vendor/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog`
4. `rm -rf ./vendor/k8s.io/kubernetes/vendor/github.com/golang/glog`
5. `make build`

**Comment by iterion** [comment] 2016-09-23 15:17
Very strange indeed. I see those same files locally:

```
./vendor/github.com/golang/glog
./vendor/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog
./vendor/k8s.io/kubernetes/vendor/github.com/golang/glog
```

But even with them still around I have no issues building. The only other culprit might be golang version?

```
=> go version
go version go1.7 linux/amd64
```

**Comment by alexdej** [comment] 2016-09-23 15:34
Maybe that's it. I have go1.6 on ubuntu, but go1.7.1 on my mac, which is having the same errors. That said, if I'm the only one hitting the issue I'm fine to close it, since I have a workaround (deleting those directories).

BTW - it's not a build error but a runtime panic.

**Comment by iterion** [comment] 2016-09-23 15:43
Ah, my bad, I was expecting a build error. I also get the panic. I'll keep investigating, I think I might know the problem.

**Comment by iterion** [comment] 2016-09-23 16:01
Does https://github.com/wearemolecule/route53-kubernetes/pull/22 fix the issue for you?

**Comment by alexdej** [comment] 2016-09-23 16:07
Yes it does!

**Comment by iterion** [comment] 2016-09-23 16:10
Great, thanks for testing. Closing this now.

**Comment by alexdej** [comment] 2016-09-23 16:11
I appreciate the quick fix!

**Closed as completed by iterion** 2016-09-23 16:10 UTC
