### ISSUE TITLE
kubernetes documentation

### ISSUE THREAD

**Issue by Moggy-the-Man** [wearemolecule/route53-kubernetes#3] opened 2016-02-17 19:12 UTC
Any chance we could get documentation regarding how to run the route53-kubernetes rc/service? on kubernetes, perhaps a .yml file? thanks

**Comment by iterion** [comment] 2016-02-17 20:58
Hello,

We currently use this rc.yaml

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: route53-kubernetes
  name: route53-kubernetes
  namespace: molecule-cluster-utils
spec:
  replicas: 1
  selector:
    app: route53-kubernetes
  template:
    metadata:
      labels:
        app: route53-kubernetes
    spec:
      containers:
      - env:
        - name: CA_FILE_PATH
          value: /opt/certs/ca.pem
        - name: CERT_FILE_PATH
          value: /opt/certs/cert.pem
        - name: KEY_FILE_PATH
          value: /opt/certs/key.pem
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /opt/creds/credentials
        image: quay.io/molecule/route53-kubernetes:v1.1.1
        name: route53-kubernetes
        volumeMounts:
        - mountPath: /opt/certs
          name: ssl-cert
          readOnly: true
        - mountPath: /opt/creds
          name: aws-creds
          readOnly: true
      volumes:
      - name: ssl-cert
        secret:
          secretName: kube-ssl
      - name: aws-creds
        secret:
          secretName: aws-creds
```

I'll go ahead and add this to the repo for future reference as well. No service is necessary as nothing is connecting directly to these pods.

The above assumes that you connect to your cluster with ssl certs (given by the secret `kube-ssl`) and that you have an IAM role set up on AWS and defined in the secret `aws-creds`.

We'd be happy to support other cluster setups, just send us a PR.

**Comment by mohanbmahajan** [comment] 2016-05-26 12:45
@iterion I created my k8s cluster using [kube-up.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/kube-up.sh) script.
Now I want to run above RC in k8s cluster to have route53 entries.
Can you tell me where can I find below,
1. /opt/certs/ca.pem
2. /opt/certs/cert.pem
3. /opt/certs/key.pem
4. /opt/creds/credentials

And how to create,
1. secretName: kube-ssl
2. secretName: aws-creds

Thanks

**Comment by osxi** [comment] 2016-07-25 22:03
Closing due to being a duplicate of https://github.com/wearemolecule/route53-kubernetes/issues/7 and will be fixed by https://github.com/wearemolecule/route53-kubernetes/pull/8.

**Closed as completed by osxi** 2016-07-25 22:03 UTC
